env:
  SEGMENT_CONTEXTS: 'ecr'
steps:
  - name: ":golang:"
    command: ".buildkite/steps/tests.sh"
    plugins:
      - docker#v3.1.0:
          image: "golang:1.13"
          workdir: /go/src/github.com/buildkite/buildkite-agent-scaler
          environment:
            - GO111MODULE=off

  - wait
  - name: ":docker:"
    command: .buildkite/steps/build-docker.sh
    # branches: master
