env:
  SEGMENT_CONTEXTS: 'aws-credentials'
steps:
  - block: ":rocket: Release ${VERSION}?"

  - label: ":s3:"
    command: ".buildkite/steps/release-version.sh"
    branches: master
    agents:
      queue: "deploy"
    concurrency: 1
    concurrency_group: 'release'

  - wait
  - label: ":github:"
    command: ".buildkite/steps/github-release.sh"
    branches: master
    agents:
      queue: "deploy"
