steps:
  - name: ":golang:"
    command: ".buildkite/steps/tests.sh"
    plugins:
      - docker#v3.5.0:
          image: "golang:1.13"
          workdir: /go/src/github.com/buildkite/buildkite-agent-scaler
          environment:
            - GO111MODULE=off

  - wait
  - name: ":docker:"
    command: .buildkite/steps/build-docker.sh
    env:
      SEGMENT_CONTEXTS: 'ecr'

  - name: ":lambda:"
    command: .buildkite/steps/build-lambda.sh
    artifact_paths:
      - handler.zip

  - wait
  - label: ":s3:"
    command: .buildkite/steps/upload-to-s3.sh
    env:
      SEGMENT_CONTEXTS: 'aws-credentials'

  - wait
  - name: ":pipeline:"
    command: .buildkite/steps/upload-release-steps.sh
    branches: master
    env:
      SEGMENT_CONTEXTS: 'aws-credentials'
